# Generated by Django 4.2.7 on 2023-11-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='Admin', max_length=20),
        ),
    ]
