# Generated by Django 4.2.7 on 2023-11-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
